# Generated by Django 4.1.5 on 2023-04-05 12:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Favicons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon_link', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Keywords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword_string', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Urls',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=100, unique=True)),
                ('page_title', models.CharField(default='', max_length=60)),
                ('page_description', models.CharField(default='', max_length=140)),
                ('icon_link', models.CharField(default='', max_length=100)),
                ('num_of_refs', models.IntegerField(default=1)),
                ('last_scrapped', models.DateTimeField(default=datetime.datetime(1, 1, 1, 0, 0))),
                ('keywords_in_it', models.ManyToManyField(to='core.keywords')),
            ],
        ),
    ]
