# Generated by Django 4.1.5 on 2023-04-18 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_urlcategory_urls_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='RootDomain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('root_url', models.CharField(max_length=100)),
                ('root_title', models.CharField(max_length=100)),
            ],
        ),
    ]
